### ISSUE TITLE
How can one effectively install `pydantic[email]`? Just adding `email-validator` as an extra dependency doesn't work

### ISSUE THREAD

**Issue by corneliusroemer** [conda-forge/pydantic-feedstock#128]
### Comment:

It seems that it's not enough to install `email-validator` from conda-forge to emulate what `pydantic[email]` does. I still get import errors telling me to pip install `pydantic[email]`. is it possible that pydantic does some extra configuration under the hood depending on whether one installs an extra or not? Generally, I thought that extras just add extra dependencies and doesn't have side effects, but here, it looks like there _are_ side effects.

**Comment by mattwthompson** [comment]
Could you share a reproduction?

**Comment by corneliusroemer** [comment]
I think I was wrong about this issue - the problem was somewhere else. Sorry for that!
