### ISSUE TITLE
Need `annotated-types` and `pydantic-core` recipe for upcoming 2.0

### ISSUE THREAD

**Issue by mattwthompson** [conda-forge/pydantic-feedstock#70]
### Comment:

The big `pydantic_core` refactor split out one of the submodules into its own package, which I don't think has been packaged onto `conda-forge` yet.

https://github.com/pydantic/pydantic/pull/4516
https://github.com/pydantic/pydantic/pull/4804

https://pypi.org/project/annotated-types/
https://github.com/annotated-types/annotated-types

https://github.com/conda-forge/staged-recipes/issues/21536

**Comment by samuelcolvin** [comment]
Correct, both annotated-types (which I co-maintain) and pydantic-core will be to be packaged for conda-forge.

**Comment by mattwthompson** [comment]
I've started the easy one: https://github.com/conda-forge/staged-recipes/pull/21537

It doesn't look like anybody's started in on `pydantic-core`, either? https://github.com/conda-forge/staged-recipes/issues?q=pydantic-core

**Comment by mattwthompson** [comment]
I have no idea how the Rust stuff works with this tooling, but if `python -m pip install .` magically works then that'd be wonderful

**Comment by samuelcolvin** [comment]
Best to have a look at watchfiles, apart from the abi3 thing, it should be similar.

`python -m pip install .` should work provided you have the rust toolchain installed.

**Comment by mattwthompson** [comment]
Okay, `annotated-types` is up. I'm working on `pydantic-core` here: https://github.com/conda-forge/staged-recipes/pull/21538

Of course let me know if you want write access to either of these feedstocks; they're your projects after all 🙂

**Comment by samuelcolvin** [comment]
Hi, yes both please.

@zac-hd and @adriangb might also like write access to annotated-types, as it's really their idea.

**Comment by pavelzw** [comment]
We can close this, right?

**Comment by pavelzw** [comment]
We can close this, right?

**Comment by mattwthompson** [comment]
Indeed
